In [1]:
from random_sample_generator import sample_generator
import dask
from dask import dataframe as dd
from scipy.stats import bernoulli, norm





self = sample_generator(10, 1000)

In [2]:
from dask.distributed import Client, progress
client = Client()

In [3]:
client

<Client: 'tcp://127.0.0.1:42783' processes=4 threads=16, memory=15.55 GiB>

In [34]:
from sympy import Symbol

x_generator = self.X_generator()
variables = self.main_effect_variables + [Symbol('y')]
def return_dict(array_x):
    y = self.get_y(array_x)
    return {var_name: [val] for var_name, val in zip(variables, array_x.tolist() + [y])}
# outputs = []
# for array_x in x_generator:
#     y = client.submit(self.get_y, array_x)
#     output = client.submit(return_dict, array_x, y)
#     outputs.append(output)

In [35]:
# import pandas as pd
# df = client.submit(pd.DataFrame, outputs)


In [36]:
from dask import bag

b = bag.from_sequence(x_generator)
output = b.map(return_dict).sum().compute()

2023-05-22 23:47:30,999 - distributed.worker - WARNING - Compute Failed
Key:       ('return_dict-sum-part-3af5277e4e00744f2bbf523414cdc896', 8)
Function:  execute_task
args:      ((<function empty_safe_apply at 0x7f69a8bc4790>, <built-in function sum>, (<function map_chunk at 0x7f69a8bc40d0>, <function return_dict at 0x7f6992182dd0>, [[array([0, 0, 0, 0, 0, 1, 1, 1, 0, 1]), array([1, 1, 1, 1, 0, 1, 1, 0, 0, 0]), array([0, 1, 0, 1, 0, 1, 1, 1, 1, 0]), array([0, 0, 0, 0, 1, 1, 0, 0, 1, 0]), array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1]), array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0]), array([1, 0, 1, 0, 1, 0, 1, 1, 0, 0]), array([1, 0, 1, 0, 1, 1, 1, 0, 0, 1]), array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0]), array([1, 1, 0, 0, 0, 0, 0, 1, 0, 1])]], None, {}), False))
kwargs:    {}
Exception: 'TypeError("unsupported operand type(s) for +: \'int\' and \'dict\'")'

2023-05-22 23:47:31,000 - distributed.worker - WARNING - Compute Failed
Key:       ('return_dict-sum-part-3af5277e4e00744f2bbf523414cdc896', 12)
Function:

TypeError: unsupported operand type(s) for +: 'int' and 'dict'

In [ ]:
output

0

In [24]:
generator = self.generator()
import dask.bag as db
import json

b = db.read_text('data/*.json').map(json.loads)
b


ValueError: An error occurred while calling the from_dict method registered to the pandas backend.
Original Message: If using all scalar values, you must pass an index

In [17]:
self.fieldnames

[x_1, x_2, x_3, x_4, x_5, x_6, x_7, x_8, x_9, x_10, y]

In [13]:
dataframes[0].compute()

TypeError: 'tuple' object is not an iterator

In [12]:
outputs = []

for i in range(self.sample_size):
    x_row = dask.delayed(bernoulli.rvs)(list(self.pi.values()), size = self.var_num)
    main_effect = self.get_main_effect_from_x_row(x_row)
    interaction_effect = self.get_interaction_effect_from_x_row(x_row)
    error = dask.delayed(norm.rvs)(scale = self.error_scale)
    y = dask.delayed(sum)([main_effect, interaction_effect, error]).compute()
    outputs.append(x_row.compute().tolist() + [y])


In [14]:
outputs

[[1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 15.192482592032851],
 [1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 15.02561578219487],
 [0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 20.418758237435995],
 [0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 17.37662928180334],
 [0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 5.428116418844233],
 [1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 10.541948740656833],
 [1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 24.394359212361632],
 [1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 10.65285969185005],
 [1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 23.93038977106503],
 [0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 12.201882501851838],
 [0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 29.93023868784628],
 [0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 16.31704181905637],
 [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 14.791099048761684],
 [0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 7.948036352326639],
 [1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 11.664345583834056],
 [1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 8.266578614977707],
 [1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 7.534564276838482],
 [1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 25.90196295838891],
 [1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 12.625804307537665],
 [1,

In [37]:
from sklearn.base import BaseEstimator, clone
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics      import r2_score

import numpy as np; import pandas as pd
from typing import List, Union

from bitstring import Bits

In [38]:
!pip install dask

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 4.1 MB/s eta 0:00:0000:0100:010m
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
  Using cached fsspec-2023.5.0-py3-none-any.whl (160 kB)
  Using cached PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)


In [42]:
from dask import dataframe as dd

ddf = dd.read_csv('tmpw1zguov5.csv')

In [163]:
def return_bitstring(x_seq):
    b = ''.join((str(z) for z in x_seq))
    bit = Bits(bin = b)
    return bit.uint

In [164]:
ddf['bits'] = ddf.loc[:, ddf.columns.str.contains('x')].apply(return_bitstring, axis = 1)

/root/barcode/.venv/lib/python3.10/site-packages/dask/dataframe/core.py:5917: UserWarning: 
You did not provide metadata, so Dask is running your function on a small dataset to guess output types. It is possible that Dask will guess incorrectly.
To provide an explicit output types or to silence this message, please provide the `meta=` keyword, as described in the map or apply function that you are using.
  Before: .apply(func)
  After:  .apply(func, meta=(None, 'int64'))

  warnings.warn(meta_warning(meta))


In [166]:
result = ddf.set_index('bits').groupby('bits').y.mean()

In [167]:
result.compute()

bits
3     -2.990150
6    -17.113382
7    -12.455653
11   -17.097339
16   -10.500701
18   -18.207829
22   -18.127595
Name: y, dtype: float64

In [104]:
result = ddf.set_index('bits').groupby('bits').y.mean()

In [105]:
result.compute()

bits
3     -2.990150
6    -17.113382
7    -12.455653
11   -17.097339
16   -10.500701
18   -18.207829
22   -18.127595
Name: y, dtype: float64

In [128]:
ddf.set_index('bits')

Dask DataFrame Structure:
                 x_1    x_2    x_3    x_4    x_5        y
npartitions=1                                            
3              int64  int64  int64  int64  int64  float64
22               ...    ...    ...    ...    ...      ...
Dask Name: sort_index, 9 graph layers

In [121]:
ddf

Dask DataFrame Structure:
                 x_1    x_2    x_3    x_4    x_5        y   bits
npartitions=1                                                   
               int64  int64  int64  int64  int64  float64  int64
                 ...    ...    ...    ...    ...      ...    ...
Dask Name: assign, 7 graph layers

In [135]:
ddf.divisions

(None, None)

In [548]:
from itertools import product, combinations
def L(barcode_length):
    def barcode_to_beta(barcode):
        if isinstance(barcode, list):
            output = [1] + barcode
        else:
            output = [1] + list(barcode)
        N = len(output)
        for i in range(2, N):
            output += [np.prod(x) for x in combinations(barcode, i)]
    #     output += [np.prod(output)]
        return output
    all_sets = list(set(product([0,1], repeat = barcode_length))); all_sets.sort()
    L = np.array([barcode_to_beta(x) for x in all_sets]).T
    return L


In [549]:
L(3)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [1]:
from importance_score import dask_parameter_generator



In [2]:
gen = dask_parameter_generator('tmpw1zguov5.csv')

In [6]:
10 // 3

3

In [565]:
gen.L.toarray()

array([[1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int8)

In [530]:
gen.MLE_SCALE

0.5345302889099425

In [531]:
gen.find_FIM().toarray().sum()*gen.MLE_VAR

10.000000000000002

In [507]:
ssto, sse = gen.find_error_statistics()

In [513]:
gen.MLE_SCALE

0.5345302889099425

In [533]:
fim = gen.find_FIM()

In [543]:
diags(list(map(lambda x: 1/x if x else float('inf'), fim.diagonal()))).toarray()

array([[inf,  0.,  0., ...,  0.,  0.,  0.],
       [ 0., inf,  0., ...,  0.,  0.,  0.],
       [ 0.,  0., inf, ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., inf,  0.,  0.],
       [ 0.,  0.,  0., ...,  0., inf,  0.],
       [ 0.,  0.,  0., ...,  0.,  0., inf]])

In [508]:
gen.MLE_SCALE

In [504]:
gen.sample_size

10

In [494]:
sse.compute()

2.857226297621466

In [455]:
gen.ddf.merge(gen.full_segment_means, how = 'left', left_index = True, right_index = True, suffixes = ['','_pred']).compute()

y     y_pred
barcode                      
3        -2.990150  -2.990150
6       -17.636538 -17.113382
6       -16.590226 -17.113382
7       -11.383768 -12.455653
7       -13.527537 -12.455653
11      -17.097339 -17.097339
16      -10.500701 -10.500701
18      -18.285188 -18.207829
18      -18.130470 -18.207829
22      -18.127595 -18.127595

In [421]:
gen.full_segment_means

barcode          y
0        3  -2.990150
1        6 -17.113382
2        7 -12.455653
3       11 -17.097339
4       16 -10.500701
5       18 -18.207829
6       22 -18.127595

In [419]:
gen

In [420]:
gen.ddf.compute()

KeyError: 7

In [400]:
gen.ddf.index

Dask Index Structure:
npartitions=1
3     uint8
22      ...
Name: barcode, dtype: uint8
Dask Name: sort_index-index, 8 graph layers

In [393]:
gen.ddf

Dask DataFrame Structure:
                     y
npartitions=1         
3              float64
22                 ...
Dask Name: sort_index, 7 graph layers

In [378]:
gen.full_segment_means.loc[3].y

-17.09733937409042

In [367]:
gen.find_FIM().toarray().sum()

10.0

In [357]:
sdiag = diags(pd.Series(gen.ddf.groupby('barcode').y.count().compute().sort_index()).reindex(list(range(2**5)), fill_value = 0))

In [358]:
type(sdiag)

scipy.sparse._dia.dia_matrix

In [355]:
sdiag.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [352]:
from scipy.sparse import diags


diags()


In [301]:
gen.sample_size

10

In [282]:
gen.gen_basic_parameters()

In [286]:
gen.ddf.shape

(Delayed('int-e2d37237-045f-4e0d-b28c-ecfc07f863f7'), 1)

In [276]:
gen.compute('dask')

Dask DataFrame Structure:
                     y
npartitions=1         
3              float64
22                 ...
Dask Name: from_pandas, 1 graph layer

In [259]:
gen.ddf.compute().to_numpy()

array([[ -2.99015048],
       [-17.63653766],
       [-16.59022621],
       [-11.38376786],
       [-13.52753723],
       [-17.09733937],
       [-10.50070062],
       [-18.28518827],
       [-18.13046978],
       [-18.12759475]])

In [258]:
gen.ddf

Dask DataFrame Structure:
                     y
npartitions=1         
3              float64
22                 ...
Dask Name: sort_index, 7 graph layers

In [212]:
gen.input_featuers

array([ True,  True,  True,  True,  True, False])

In [204]:
gen.ddf.apply(gen.return_bitstring, axis = 1)

ValueError: Metadata inference failed in `apply`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
TypeError("dask_parameter_generator.return_bitstring() missing 1 required positional argument: 'x_seq'")

Traceback:
---------
  File "/root/barcode/.venv/lib/python3.10/site-packages/dask/dataframe/utils.py", line 193, in raise_on_meta_error
    yield
  File "/root/barcode/.venv/lib/python3.10/site-packages/dask/dataframe/core.py", line 6810, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/root/barcode/.venv/lib/python3.10/site-packages/dask/utils.py", line 1105, in __call__
    return getattr(__obj, self.method)(*args, **kwargs)
  File "/root/barcode/.venv/lib/python3.10/site-packages/pandas/core/frame.py", line 9433, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/root/barcode/.venv/lib/python3.10/site-packages/pandas/core/apply.py", line 678, in apply
    return self.apply_standard()
  File "/root/barcode/.venv/lib/python3.10/site-packages/pandas/core/apply.py", line 798, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/root/barcode/.venv/lib/python3.10/site-packages/pandas/core/apply.py", line 814, in apply_series_generator
    results[i] = self.f(v)


In [192]:
gen.ddf

Dask DataFrame Structure:
                 x_1    x_2    x_3    x_4    x_5        y
npartitions=1                                            
               int64  int64  int64  int64  int64  float64
                 ...    ...    ...    ...    ...      ...
Dask Name: read-csv, 1 graph layer

In [189]:
ddf = dd.read_csv('tmpw1zguov5.csv')
ddf

Dask DataFrame Structure:
                 x_1    x_2    x_3    x_4    x_5        y
npartitions=1                                            
               int64  int64  int64  int64  int64  float64
                 ...    ...    ...    ...    ...      ...
Dask Name: read-csv, 1 graph layer

In [186]:
gen.ddf

<module 'dask.dataframe' from '/root/barcode/.venv/lib/python3.10/site-packages/dask/dataframe/__init__.py'>

In [118]:
dask.dataframe

TypeError: 'module' object is not callable

In [159]:
from bitstring import BitArray, Bits

x = Bits(bin = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111")
y = Bits(bin = "1111111111111111111111111111111111")

In [160]:
type(x.uint)

int

In [162]:
type(x.uintbe)

int